In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
from sklearn.preprocessing import scale
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from PIL import Image
from sklearn.metrics import accuracy_score

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import AnovaRM

from matplotlib import pyplot as plt
from matplotlib import pyplot
import seaborn as sns
import xgboost as xgb
from sklearn.naive_bayes import GaussianNB

from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier
from sklearn.feature_selection import RFE

In [2]:
dt = DecisionTreeClassifier()
rf = RandomForestClassifier(n_estimators=100, random_state=0, n_jobs = -1)
logreg = LogisticRegression(solver='liblinear',multi_class='ovr')
svm = SVC(gamma='auto')
xgb = xgb.XGBClassifier()
gnb = GaussianNB()

In [3]:
database1 = pd.read_csv("data.csv", sep=';')
database1.head()

MUSK   2    3    4   5    6   7   8    9  10  ...  159  160  161  162  163  \
0  MUSK  46 -108  -60 -69 -117  49  38 -161  -8  ... -308   52   -7   39  126   
1  MUSK  41 -188 -145  22 -117  -6  57 -171 -39  ...  -59   -2   52  103  136   
2  MUSK  46 -194 -145  28 -117  73  57 -168 -39  ... -134 -154   57  143  142   
3  MUSK  41 -188 -145  22 -117  -7  57 -170 -39  ...  -60   -4   52  104  136   
4  MUSK  41 -188 -145  22 -117  -7  57 -170 -39  ...  -60   -4   52  104  137   

   164  165  166  167  168  
0  156  -50 -112   96  1.0  
1  169  -61 -136   79  1.0  
2  165  -67 -145   39  1.0  
3  168  -60 -135   80  1.0  
4  168  -60 -135   80  1.0  

[5 rows x 168 columns]

In [4]:
X = database1.drop(["MUSK","168"],axis=1)
y = database1['168']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.10 )

In [5]:
def model(name):
    name.fit(X_train, y_train)
    y_pred = name.predict(X_test)
    score= accuracy_score(y_test, y_pred) * 100
    print(str(name) + "Accuracy:",score)
    report_name=classification_report(y_test, y_pred)
    print(report_name)
    print(confusion_matrix(y_test,y_pred))

In [7]:
def rfe(model):  
    rfe = RFE(model, 16)
    fit = rfe.fit(X, y)
    print("Num Features: %s" % (fit.n_features_))
    print("Selected Features: %s" % (fit.support_))
    print("Feature Ranking: %s" % (fit.ranking_))

In [8]:
def crossval(model):
    scores=cross_val_score(model, X, y, cv=10, scoring ="accuracy")
    print(str(model) + "Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [9]:
model(dt)
crossval(dt)
rfe(dt)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')Accuracy: 96.36363636363636
              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       557
         1.0       0.87      0.90      0.89       103

    accuracy                           0.96       660
   macro avg       0.93      0.94      0.93       660
weighted avg       0.96      0.96      0.96       660

[[543  14]
 [ 10  93]]
DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrea

In [10]:
model(rf)
crossval(rf)
rfe(rf)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)Accuracy: 98.48484848484848
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       557
         1.0       0.99      0.91      0.95       103

    accuracy                           0.98       660
   macro avg       0.99      0.96      0.97       660
weighted avg       0.98      0.98      0.98       660

[[556   1]
 [  9  94]]
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
        

In [11]:
model(logreg)
crossval(logreg)
rfe(logreg)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)Accuracy: 95.3030303030303
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97       557
         1.0       0.86      0.83      0.85       103

    accuracy                           0.95       660
   macro avg       0.91      0.90      0.91       660
weighted avg       0.95      0.95      0.95       660

[[543  14]
 [ 17  86]]
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
   

In [13]:
model(svm)
crossval(svm)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)Accuracy: 90.9090909090909
              precision    recall  f1-score   support

         0.0       0.90      1.00      0.95       557
         1.0       1.00      0.42      0.59       103

    accuracy                           0.91       660
   macro avg       0.95      0.71      0.77       660
weighted avg       0.92      0.91      0.89       660

[[557   0]
 [ 60  43]]
SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)Accuracy: 0.85 (+/- 0.01)


In [14]:
model(xgb)
crossval(xgb)
rfe(xgb)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)Accuracy: 97.12121212121212
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98       557
         1.0       0.95      0.86      0.90       103

    accuracy                           0.97       660
   macro avg       0.96      0.93      0.94       660
weighted avg       0.97      0.97      0.97       660

[[552   5]
 [ 14  89]]
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learnin

In [16]:
model(gnb)
crossval(gnb)


GaussianNB(priors=None, var_smoothing=1e-09)Accuracy: 84.84848484848484
              precision    recall  f1-score   support

         0.0       0.96      0.86      0.91       557
         1.0       0.51      0.79      0.62       103

    accuracy                           0.85       660
   macro avg       0.73      0.82      0.76       660
weighted avg       0.89      0.85      0.86       660

[[479  78]
 [ 22  81]]
GaussianNB(priors=None, var_smoothing=1e-09)Accuracy: 0.80 (+/- 0.31)


In [3]:
database2 = pd.read_csv("shuttle-train.csv", sep=';')
database2.head()

f1  f2  f3  f4  f5  f6  f7  f8  f9  d
0  50  21  77   0  28   0  27  48  22  2
1  55   0  92   0   0  26  36  92  56  4
2  53   0  82   0  52  -5  29  30   2  1
3  37   0  76   0  28  18  40  48   8  1
4  37   0  79   0  34 -26  43  46   2  1

In [4]:
database3 = pd.read_csv("shuttle-test.csv", sep=';')
database3.head()

f1  f2  f3  f4  f5  f6  f7  f8  f9  d
0  55   0  81   0  -6  11  25  88  64  4
1  56   0  96   0  52  -4  40  44   4  4
2  50  -1  89  -7  50   0  39  40   2  1
3  53   9  79   0  42  -2  25  37  12  4
4  55   2  82   0  54  -6  26  28   2  1

In [5]:
X1_train = database2.drop(["d"], axis=1)
X1_test = database3.drop(["d"], axis=1)
y1_train = database2['d']
y1_test = database3['d']

In [6]:
def model1(name):
    name.fit(X1_train, y1_train)
    y1_pred = name.predict(X1_test)
    score= accuracy_score(y1_test, y1_pred) * 100
    print(str(name) + "Accuracy:",score)
    report_name=classification_report(y1_test, y1_pred)
    print(report_name)
    print(confusion_matrix(y1_test,y1_pred))

In [8]:
def rfe1(model):    
    rfe = RFE(model, 3)
    fit = rfe.fit(df_row_reindex_X, df_row_reindex_y)
    print("Num Features: %s" % (fit.n_features_))
    print("Selected Features: %s" % (fit.support_))
    print("Feature Ranking: %s" % (fit.ranking_))

In [7]:
df_row_reindex = pd.concat([database2, database3], ignore_index=True)
df_row_reindex_X = df_row_reindex.drop(["d"], axis=1)
df_row_reindex_y = df_row_reindex['d']

In [8]:
def crossval(model):
    scores=cross_val_score(model, df_row_reindex_X, df_row_reindex_y, cv=10, scoring ="accuracy")
    print(str(model) + "Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [ ]:
model1(SVC(gamma='auto'))
crossval(SVC(gamma='auto'))

In [24]:
model1(dt)
crossval(dt)
rfe1(dt)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')Accuracy: 99.98620689655172
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     11478
           2       1.00      0.92      0.96        13
           3       1.00      1.00      1.00        39
           4       1.00      1.00      1.00      2155
           5       1.00      1.00      1.00       809
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00         2

    accuracy                           1.00     14500
   macro avg       1.00      0.99      0.99     14500
weig

In [25]:
model1(rf)
crossval(rf)
rfe1(rf)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)Accuracy: 99.97931034482758
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     11478
           2       1.00      0.92      0.96        13
           3       0.97      1.00      0.99        39
           4       1.00      1.00      1.00      2155
           5       1.00      1.00      1.00       809
           6       1.00      0.75      0.86         4
           7       1.00      0.50      0.67         

In [26]:
model1(logreg)
crossval(logreg)
rfe1(logreg)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)Accuracy: 93.10344827586206
              precision    recall  f1-score   support

           1       0.93      0.99      0.96     11478
           2       0.00      0.00      0.00        13
           3       0.00      0.00      0.00        39
           4       0.91      0.61      0.73      2155
           5       1.00      1.00      1.00       809
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         2

    accuracy                           0.93     14500
   macro avg       0.41      0.37      0.38     14500
weighted avg       0.93      0.93      0.92     14500

[[11372     0     0   104     0     0     2]
 [

C:\Users\Ahmet\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)Accuracy: 0.93 (+/- 0.01)
Num Features: 3
Selected Features: [False False False False  True False  True  True False]
Feature Ranking: [4 5 2 6 1 7 1 1 3]


In [11]:
model1(xgb)
crossval(xgb)
rfe1(xgb)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)Accuracy: 99.99310344827586
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     11478
           2       1.00      0.92      0.96        13
           3       1.00      1.00      1.00        39
           4       1.00      1.00      1.00      2155
           5       1.00      1.00      1.00       809
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00         2

    accuracy                           1.00     14500
   macro avg    

In [11]:
model1(gnb)
crossval(gnb)

GaussianNB(priors=None, var_smoothing=1e-09)Accuracy: 82.6551724137931
              precision    recall  f1-score   support

           1       0.95      0.88      0.92     11478
           2       0.01      0.92      0.02        13
           3       0.11      0.59      0.19        39
           4       0.89      0.54      0.67      2155
           5       0.99      0.82      0.90       809
           6       0.40      1.00      0.57         4
           7       0.00      1.00      0.01         2

    accuracy                           0.83     14500
   macro avg       0.48      0.82      0.47     14500
weighted avg       0.94      0.83      0.88     14500

[[10116   463   185   143     4     5   562]
 [    1    12     0     0     0     0     0]
 [    7     1    23     0     1     0     7]
 [  502   491     0  1162     0     0     0]
 [    0   142     0     0   666     1     0]
 [    0     0     0     0     0     4     0]
 [    0     0     0     0     0     0     2]]
GaussianNB(prior